name: "🐞 Bug Report"
description: "Relate um bug"
title: "[Bug]: <título curto>"
labels: ["bug"]
body:
  - type: textarea
    id: ambiente
    attributes:
      label: "🌐 Ambiente"
      placeholder: |
        Ambiente: Homologação
        Usuário: usuario@exemplo.com
        Organização: Provanza
    validations:
      required: true
  - type: textarea
    id: passos
    attributes:
      label: "🪜 Passos para Reproduzir"
      placeholder: |
        1) ...
        2) ...
    validations:
      required: true
  - type: textarea
    id: atual
    attributes:
      label: "📍 Resultado atual"
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: "✅ Resultado esperado"
    validations:
      required: true
